### PR TITLE
Review _create_grid() method

### PR DESCRIPTION
**Pull request by kevin-hausmann**
I updated to base class' _create_grid() method to support padding and to return the resulting grid's dimensions. This will allow Beirle and Fioletov to use it instead of providing their own implementation.

I.e., from

```python
gp_sources, min_long, max_long, min_lat, max_lat, nlon, nlat = self._get_source_grid_settings(region, add_region_offset)
```
you can now move to

```python
gp_sources, (nlon, nlat) = self._create_grid(region, resolution_lon, resolution_lat, padding=(add_region_offset[0], add_region_offset[1])
min_long, min_lat, max_long, max_lat = gp_sources.total_bounds
```

### CODE REVIEW

**Review by enricodammers — CHANGES_REQUESTED** [review]
Thanks for the edits. Will include it into beirle/fioletov.

One edit needed:
 def _create_grid(region: MultiPolygon, width: float, height: float,
                     padding: tuple[float, float] = (0., 0.), snap: bool = False,
                     include_center_cols: bool = False, crs: str = "EPSG:4326") -> tuple[GeoDataFrame, tuple[int, int]]:

Didnt work directly on my end, and i assume not all users will switch to the required version of python; tuple(a,b) needs to be tuple([a,b]) as it only has one argument.

def _create_grid(region: MultiPolygon, width: float, height: float,
   ...:                      padding: tuple([float, float]) = (0., 0.), snap: bool = False,
   ...:                      include_center_cols: bool = False, crs: str = "EPSG:4326") -> tuple([GeoDataFrame, tuple([int, int])]):

**Comment by kevin-hausmann** [comment]
Thanks Enrico! I do not understand what `tuple([float, float])` is supposed to signify? Please check the docs at https://docs.python.org/3/library/typing.html#typing.Tuple - we could `import Tuple from typing` and move to `Tuple[a, b]` but since this is deprecated, I would rather not do this.
We do require python >=3.9 elsewhere as well, so I do think the current version is fine. Please disagree if you have to, could you provide the error message you are seeing?

**Comment by enricodammers** [comment]
> 

Thats amusing; 
i've been using this section; https://docs.python.org/3/library/stdtypes.html#tuples
The error that i get is: TypeError: 'type' object is not subscriptable
I get similar errors for sections with "`dict[str, DataFrame]`" 

To me (as a former 2.7 and older user) this seems logical as you're trying to pass multiple variables at once + anything with square brackets [] typically means you're trying to subscript it/retrieve a value from a set.

Now it wouldn't surprise me if something has been added since. But i didn't expect such a huge change between python 3.8.8 and 3.9.4.

I solved the current problem by changing it to a list within the tuple... to signify that you want two values in tuple form. 
The dict[str,DataFrame] issues i resolved by turning it all into lists, although the correct way would probably be dict([str, str]) as we're actually returning 2 dictionary entries of which one happens to be a DataFrame.

**Comment by kevin-hausmann** [comment]
Ahh, okay, I see where you are coming from now. You cannot "parse" code the same way you parse type hints. There is not "subscription" for a type hint, that's why the [ ] can be reused. PEP 585 (new in Python 3.9) makes type hinting to standard types better and less confusing, see https://www.python.org/dev/peps/pep-0585/ - I think that's perfectly fine and we should stick with that.
Please move your environment to Python >= 3.9 and all these problems will go away. Generally note that you should never use lists as parameters with default values since list are mutable (tuples are fine and immutable).

**Pull request merged**
