### PR TITLE
Make run() method return table/grid-tuple instead of dict

### PR DESCRIPTION
**Pull request by kevin-hausmann**
Hi guys, working on the create grid method, I realized that the run() method could just return both the table and the grid. This allows us to get rid of the constants for the dict keys and also simplifies the call code

```python
table, grid = method.run(...)
```

vs.

```python
result = method.run(...)
table = result[BeirleEmissionsCalculator.TOTAL_KEY]
grid = result[BeirleEmissionsCalculator.GRID_KEY]
```

### CODE REVIEW

**Comment by jptokaya** [comment]
Yes I agree, to me this is more intuitive: 

table, grid = method.run(...)

**Review by Christian-Mielke — APPROVED** [review]
Yes that looks better to me as well.

**Review by enricodammers — APPROVED** [review]
Looks good to me, this also removes the upcoming issue with "-->dict[str,DataFrame]" which does not seem to be valid/allowed in the newest python versions...

**Comment by kevin-hausmann** [comment]
> Looks good to me, this also removes the upcoming issue with "-->dict[str,DataFrame]" which does not seem to be valid/allowed in the newest python versions...

Interesting, can you provide a link where this change is explained, just to understand what the issue is? Thanks!

**Comment by kevin-hausmann** [comment]
Hey @Christian-Mielke @jptokaya @enricodammers I fully implemented this now. The result is now a "namedtuple" from the Python "collections" package, allowing for easy access by index and name. I added a `_create_result_tuple()` method to base.py for easy creation. Please have a look, if you do not disagree, I will update the documentation and merge into main soon.

**Review by jptokaya — APPROVED** [review]

**Pull request merged**
