### PR TITLE
Add time aggregation parameter to run method

### PR DESCRIPTION
**Pull request by kevin-hausmann**

### CODE REVIEW

**Comment by enricodammers** [comment]
Looks fine to me. Potentially include something like "full time span" as an option, without any other aggregation provided.
But as that's already part of the output we can leave it out here.

Janot is on leave, working on his house, so i'll be the only one commenting from our side this week.

**Review by enricodammers — APPROVED** [review]
Looks fine to me. Potentially include something like "full time span" as an option, without any other aggregation provided.
But as that's already part of the output we can leave it out here.

**Comment by kevin-hausmann** [comment]
Hi all, this took a while, but I feel better about this change now. I integrated the new parameter to all existing code and added proper testing. @Christian-Mielke and @jptokaya - could you please also have a look and let me know if you agree? Thanks!

**Comment by jptokaya** [comment]
Great! Looks good to me as well. Should we also allow a weekly option or would we say that is too fine as well? I agree with Enrico that a full period option would be nice to implement if people want to look at a specific event for example.

**Review by jptokaya — APPROVED** [review]

**Comment by kevin-hausmann** [comment]
Hi @jptokaya  and @enricodammers - thanks for your feedback!

> Great! Looks good to me as well. Should we also allow a weekly option or would we say that is too fine as well?

I was considering to implement WEEKLY as well, but I did not really see the point right now. I feel this could be added at a later stage, please disagree if you have a use-case in mind!

> I agree with Enrico that a full period option would be nice to implement if people want to look at a specific event for example.

The "full period option" confuses me and makes me think (again) that we are not on the same page. Of course, the data for the complete period specified is always calculated and returned (in the main result table as well as the totals column in the gridded result table) - am I missing your point?

**Comment by jptokaya** [comment]
Hi Kevin, agreed! Weekly can be added at a later point if needed. I don't see a particular use case atm. Since the full period is always calculated I'm happy and you can disregard my previous remark

**Comment by kevin-hausmann** [comment]
> Hi @kevin-hausmann, agreed! Weekly can be added at a later point if needed. I don't see a particular use case atm. Since the full period is always calculated I'm happy and you can disregard my previous remark

Okay, great. Please make sure you REALLY understand the details at https://github.com/UBA-DE-Emissionsituation/space-emissions/wiki/Emission-deriving-methods - this needs to be implemented by your method(s). I tried to specify as clearly as I could what results to put where. If any of that is unclear, please let me know so I can fix that - thanks!

**Pull request merged**
