### PR TITLE
Download tools update for era5 winddata and tropomi download

### PR DESCRIPTION
**Pull request by jptokaya**
Tools are designed to be more general and allow data download from other (sentinel) satellites and other ERA5 data. The TROPOMI downloads are generally probably not required, since most data is already on the hyperspec. If people want to store data somewhere else these tools will come in handy

### CODE REVIEW

**Review by Christian-Mielke — CHANGES_REQUESTED** [review]
Well done Janot I think this works with a few mod. suggestions:

see my mail.

**Comment by enricodammers** [comment]
Small .md file with an explanation (like our earlier emails) would be nice.

As for the Ipybn: either that or just an interactive python file with some further comments.

**Comment by Christian-Mielke** [comment]
One quick question: Why do you use cdsapi and not the builtin download all options of sentinelsat?

**Comment by jptokaya** [comment]
> options

Hi Christian, the cdsapi is used to collect climatological data (ERA5 wind field). I do not think the sentinel sat api is able to do the same. Have I overlooked some functionality of the sentinelsat package/api?

**Comment by Christian-Mielke** [comment]
> > options
> 
> Hi Christian, the cdsapi is used to collect climatological data (ERA5 wind field). I do not think the sentinel sat api is able to do the same. Have I overlooked some functionality of the sentinelsat package/api?

Sorry my fault, you were right.

**Comment by kevin-hausmann** [comment]
Is this still relevant? Otherwise @jptokaya please close and delete the underlying branch - thanks!

**Pull request closed without merging**
